force-app/main/default/objects/Case/fields/Email_Sender__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Email Sender</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
 * Created by kamil on 12.07.2023.
 */

public with sharing class CaseTriggerHandler {

    public static void addEmailSender(List<Case> newCases){
        Map<String, Id> emailsMap = new Map<String, Id>();

        for (Case casee : newCases){
            emailsMap.put(casee.SuppliedEmail, null);
        }

        for (Person__c person : [SELECT Id, Email__c FROM Person__c WHERE Email__c IN :emailsMap.keySet()]){
            emailsMap.put(person.Email__c, person.Id);
        }

        for (Case casee : newCases){
            if (emailsMap.containsKey(casee.SuppliedEmail)) {
                casee.Email_Sender__c = emailsMap.get(casee.SuppliedEmail);
            }
        }
    }

}