force-app/main/default/objects/Case/fields/Email_Sender__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Email Sender</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/Tests/CaseTriggerHandlerTest.cls
/**
 * Created by kamil on 12.07.2023.
 */

@IsTest
public with sharing class CaseTriggerHandlerTest {

    private static List<String> emails = new List<String>{'test1@example.com','test2@example.com','test3@example.com'};
    @IsTest
    static void testAddEmailSender() {
        List<Case> newCases = new List<Case>();

        Case case1 = new Case(
                Status = CaseConst.INSTANCE.STATUS.NEW_CASE,
                Reason = CaseConst.INSTANCE.CASE_ORIGIN.EMAIL,
                SuppliedEmail = emails.get(0)
        );
        Case case2 = new Case(
                Status = CaseConst.INSTANCE.STATUS.NEW_CASE,
                Reason = CaseConst.INSTANCE.CASE_ORIGIN.EMAIL,
                SuppliedEmail = emails.get(1)
        );
        Case case3 = new Case(
                Status = CaseConst.INSTANCE.STATUS.NEW_CASE,
                Reason = CaseConst.INSTANCE.CASE_ORIGIN.EMAIL,
                SuppliedEmail = emails.get(2)
        );
        newCases.add(case1);
        newCases.add(case2);
        newCases.add(case3);

        Person__c person1 = new Person__c(Name = 'Test',Last_Name__c = 'Test',Email__c = emails.get(0));
        Person__c person2 = new Person__c(Name = 'Test',Last_Name__c = 'Test',Email__c = emails.get(1));
        insert new List<Person__c>{person1, person2};

        Test.startTest();
        CaseTriggerHandler.addEmailSender(newCases);
        Test.stopTest();

        Assert.areEqual(person1.Id,case1.Email_Sender__c, String.format('Unexpected Email_Sender__c for {0}',emails));
        Assert.areEqual(person2.Id,case2.Email_Sender__c, String.format('Unexpected Email_Sender__c for {1}',emails));
        Assert.isNull(case3.Email_Sender__c, String.format('Email_Sender__c for {2} should be null',emails));
    }
}