force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adventure Novel</fullName>
            </value>
            <value>
                <fullName>Autobiography</fullName>
            </value>
            <value>
                <fullName>Crime Fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Short Story</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Lector__c.field-meta.xml
<CustomField>
    <fullName>Lector__c</fullName>
    <defaultValue>&quot;unknown&quot;</defaultValue>
    <label>Lector</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Publishing_House__c.field-meta.xml
<CustomField>
    <fullName>Publishing_House__c</fullName>
    <label>Publishing House</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Item__c.Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>

</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MultiLoanCreatorController.cls
/**
 * Created by kamil on 23.07.2023.
 */

public with sharing class MultiLoanCreatorController {
  @AuraEnabled(Cacheable=true)
  public static List<Item__c> getItems(
    String name,
    String type,
    String genre,
    String additionalFiler
  ) {
    if (type.equals(Consts.ITEMS.TYPE.PAPER_BOOK)) {
      return [
        SELECT Id, Name, Type__c
        FROM Item__c
        WHERE
          Name LIKE :'%' + name + '%'
          AND Type__c = :type
          AND Genre__c LIKE :'%' + genre + '%'
      ];
    } else if (type.equals(Consts.ITEMS.TYPE.MAGAZINE)) {
      return [
        SELECT Id, Name, Type__c
        FROM Item__c
        WHERE
          Name LIKE :'%' + name + '%'
          AND Type__c = :type
          AND Publishing_House__c LIKE :'%' + additionalFiler + '%'
      ];
    } else if (type.equals(Consts.ITEMS.TYPE.AUDIOBOOK)) {
      return [
        SELECT Id, Name, Type__c
        FROM Item__c
        WHERE
          Name LIKE :'%' + name + '%'
          AND Type__c = :type
          AND Lector__c LIKE :'%' + additionalFiler + '%'
      ];
    } else {
      return [
        SELECT Id, Name, Type__c
        FROM Item__c
        WHERE Name LIKE :'%' + name + '%'
      ];
    }
  }

  @AuraEnabled
  public static void updateLoans(List<Loan__c> loans) {
    for (Loan__c loan : loans) {
      loan.Status__c = Consts.LOANS.STATUS.RETURNED;
    }

    update loans;
  }
}