force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adventure Novel</fullName>
            </value>
            <value>
                <fullName>Autobiography</fullName>
            </value>
            <value>
                <fullName>Crime Fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Short Story</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Available</label>
    <type>Checkbox</type>

</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Version</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ItemSearcherController.cls
public with sharing class ItemSearcherController {
  private static final String TYPE_FIELD_TEMPLATE = '{0} AND {1} = \'\'{2}\'\'';
  private static final String VERSION_FIELD_TEMPLATE = '{0} AND {1} = {2}';
  private static final String TEXT_FIELD_TEMPLATE = '{0} AND {1} LIKE \'\'{2}%\'\'';
  @AuraEnabled
  public static List<Item__c> searchItems(
    Map<String, String> searchProperties
  ) {
    Map<String, String> templates = new Map<String, String>();
    templates.put(Item__c.Type__c.getDescribe().name, TYPE_FIELD_TEMPLATE);
    templates.put(
      Item__c.Version__c.getDescribe().name,
      VERSION_FIELD_TEMPLATE
    );
    String baseQuery = 'SELECT Id,Name,Type__c,Genre__c FROM Item__c WHERE Is_Available__c = TRUE';

    for (String field : searchProperties.keySet()) {
      if (String.isNotBlank(searchProperties.get(field))) {
        String escaped = String.escapeSingleQuotes(searchProperties.get(field));
        if (templates.containsKey(field)) {
          baseQuery = String.format(
            templates.get(field),
            new List<String>{ baseQuery, field, escaped }
          );
        } else {
          baseQuery = String.format(
            TEXT_FIELD_TEMPLATE,
            new List<String>{ baseQuery, field, escaped }
          );
        }
      }
    }
    return Database.query(baseQuery);
  }
}