force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adventure Novel</fullName>
            </value>
            <value>
                <fullName>Autobiography</fullName>
            </value>
            <value>
                <fullName>Crime Fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Short Story</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <label>Borrower</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Item__c.Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>

</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Maximum_Number_Of_Rentals__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Number_Of_Rentals__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Number Of Rentals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Tests/DataFactoryTest.cls
/**
 * Created by kamil on 15.07.2023.
 */
@IsTest
public with sharing class DataFactoryTest {

    private static final Integer numberOfData = 5;
    private static final Integer maxRentals = 2;
    private static final String prefix = 'Test';
    private static final String emailPrefix = 'testEmail';


    @IsTest
    public static void createItemsListTest(){
        DataFactory.createItemsList(numberOfData,true,prefix,Consts.ITEMS.TYPE.PAPER_BOOK,Consts.ITEMS.GENRE.SCIENCE_FICTIN);

        List<Item__c> books = [SELECT Name,Type__c,Genre__c FROM Item__c];

        Assert.areEqual(numberOfData,books.size(),'Incorrect number of inserted items');

        for(Integer i = 0; i < numberOfData;i++){
            Assert.areEqual(books.get(i).Name,prefix+' '+i,'Incorrect name of item #'+i);
            Assert.areEqual(books.get(i).Type__c,Consts.ITEMS.TYPE.PAPER_BOOK,'Incorrect type of item #'+i);
            Assert.areEqual(books.get(i).Genre__c,Consts.ITEMS.GENRE.SCIENCE_FICTIN,'Incorrect genre of item #'+i);
        }
    }

    @IsTest
    public static void createPeopleList(){
        DataFactory.createPeopleList(numberOfData,true,prefix,'testEmail',maxRentals);

        List<Person__c> people = [SELECT Name,Email__c,Maximum_Number_Of_Rentals__c FROM Person__c];

        Assert.areEqual(numberOfData,people.size(),'Incorrect number of inserted people');

        for(Integer i = 0; i < numberOfData;i++){
            Assert.areEqual(people.get(i).Name,prefix+' '+i,'Incorrect name of person #'+i);
            Assert.areEqual(people.get(i).Email__c,emailPrefix+i+'@gmail.com','Incorrect email of person #'+i);
            Assert.areEqual(people.get(i).Maximum_Number_Of_Rentals__c,maxRentals,'Incorrect number of maximum rentals of person #'+i);
        }
    }

    @IsTest
    public static void createLoansList(){
        List<Item__c> items = DataFactory.createItemsList(numberOfData,true,prefix,Consts.ITEMS.TYPE.PAPER_BOOK,Consts.ITEMS.GENRE.SCIENCE_FICTIN);

        List<Person__c> people = DataFactory.createPeopleList(numberOfData,true,prefix,'testEmail',maxRentals);

        DataFactory.createLoansList(numberOfData,true,items,people,Date.today(),Date.today()+1,Consts.LOANS.STATUS.BORROWED);


        List<Loan__c> loans = [SELECT Item__c,Borrower__c,Status__c FROM Loan__c];

        Assert.areEqual(numberOfData,loans.size(),'Incorrect number of inserted loans');

        for(Integer i = 0; i < numberOfData;i++){
            Assert.areEqual(loans.get(i).Item__c,items.get(i).Id+' '+i,'Incorrect Item of item #'+i);
            Assert.areEqual(loans.get(i).Borrower__c,people.get(i).Id+' '+i,'Incorrect Borrower of loan #'+i);
            Assert.areEqual(loans.get(i).Status__c,Consts.LOANS.STATUS.BORROWED,'Incorrect Status of loan #'+i);
        }
    }

}