force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/End_Of_Rental__c.field-meta.xml
<CustomField>
    <fullName>End_Of_Rental__c</fullName>
    <label>End Of Rental</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Item__c.Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>

</CustomField>

force-app/main/default/objects/Loan__c/fields/Penalty__c.field-meta.xml
<CustomField>
    <fullName>Penalty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Penalty</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PenaltyCharge.cls
/**
 * Created by kamil on 19.07.2023.
 */

public with sharing class PenaltyCharge {
    public static final String JOB_NAME = 'Penalty Charge Job';
    public static Id scheduleMe() {
        ReturnReminder schedule = new ReturnReminder();
        return System.schedule(JOB_NAME, Consts.CRONS.CRON.PENALTY_CHARGE, schedule);
    }

    public void execute(SchedulableContext context) {
        List<Loan__c> delayedLoans = [SELECT Item__r.Type__c, Penalty__c, End_Of_Rental__c FROM Loan__c WHERE Status__c = :Consts.LOANS.STATUS.DELAY AND End_Of_Rental__c < :Date.today()];

        for (Loan__c loan : delayedLoans) {
            loan.Penalty__c = chargeFromItemType(loan.Item__r.Type__c) * calculateWorkingDays(loan.End_Of_Rental__c, Date.today());
        }

        update delayedLoans;
    }

    @TestVisible
    private static Double chargeFromItemType(String itemType) {
        if (itemType.equals(Consts.ITEMS.TYPE.PAPER_BOOK)) {
            return Consts.LOANS.CHARGE.BOOK_CHARGE;
        } else if (itemType.equals(Consts.ITEMS.TYPE.MAGAZINE)) {
            return Consts.LOANS.CHARGE.MAGAZINE_CHARGE;
        } else if (itemType.equals(Consts.ITEMS.TYPE.AUDIOBOOK)) {
            return Consts.LOANS.CHARGE.AUDIOBOOK_CHARGE;
        } else {
            return 0;
        }
    }
    @TestVisible
    private static Integer calculateWorkingDays(Date startDate, Date endDate) {
        if (startDate > endDate) {
            throw new IncorrectDateOrderException('startDate cannot be greater than endData');
        }

        Integer workingDays = 0;
        Datetime currentDate = startDate;
        while (currentDate < endDate) {
            currentDate = currentDate.addDays(1);
            if (!(currentDate.format('E').equals('Sat') || currentDate.format('E').equals('Sun'))) {
                workingDays++;
            }
        }
        return workingDays;
    }

}