force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adventure Novel</fullName>
            </value>
            <value>
                <fullName>Autobiography</fullName>
            </value>
            <value>
                <fullName>Crime Fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Short Story</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <label>Borrower</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/End_Of_Rental__c.field-meta.xml
<CustomField>
    <fullName>End_Of_Rental__c</fullName>
    <label>End Of Rental</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Item__c.Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>

</CustomField>

force-app/main/default/objects/Loan__c/fields/Rental_Date__c.field-meta.xml
<CustomField>
    <fullName>Rental_Date__c</fullName>
    <label>Rental Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Maximum_Number_Of_Rentals__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Number_Of_Rentals__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Number Of Rentals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Tests/DelayedItemsTest.cls
@IsTest
private class DelayedItemsTest {

  private static final Date CURRENT_DATA = Date.today();
  private static final String BOOK_NAME = 'Test Book';
  private static final String BORROWER_NAME = 'Test';
  @TestSetup
  private static void insertBasicData() {
    Item__c book = new Item__c(
            Name = BOOK_NAME,
            Type__c = Consts.ITEMS.TYPE.PAPER_BOOK,
            Genre__c = Consts.ITEMS.GENRE.NOVEL
    );
    insert book;

    Person__c borrower = new Person__c(
            Name = BORROWER_NAME,
            Last_Name__c = 'Borrower',
            Email__c = 'testEmail@gmail.com',
            Maximum_Number_Of_Rentals__c = 2
    );
    insert borrower;
  }
  @IsTest
  static void chechDelayedItems() {
    List<Loan__c> newLoans = new List<Loan__c>();

    Item__c book = [
            SELECT Id, Type__c
            FROM Item__c
            WHERE Name = :BOOK_NAME
    ];
    Person__c borrower = [
            SELECT Id, Maximum_Number_Of_Rentals__c
            FROM Person__c
            WHERE Name = :BORROWER_NAME
    ];

    for (Integer i = 1; i <= 5; i++) {
      Loan__c loan = new Loan__c(
        Name = 'Test Loan',
        Item__c = book.Id,
        Borrower__c = borrower.Id,
        Status__c = Consts.LOANS.STATUS.BORROWED,
        Rental_Date__c = CURRENT_DATA.addDays(-(5 + 1)),
        End_Of_Rental__c = CURRENT_DATA.addDays(-i)
      );

      newLoans.add(loan);
    }

    insert newLoans;

    Test.startTest();
    DelayedItems scheduler = new DelayedItems();
    scheduler.execute(null);
    Test.stopTest();

    List<Loan__c> updatedLoans = [
      SELECT Id, Status__c
      FROM Loan__c
      WHERE Id IN :newLoans
    ];

    for (Loan__c updatedLoan : updatedLoans) {
      System.assertEquals(Consts.LOANS.STATUS.DELAY, updatedLoan.Status__c);
    }
  }

  @IsTest
  static void chechNoDelayedItems() {
    List<Loan__c> newLoans = new List<Loan__c>();

    Item__c book = [
            SELECT Id, Type__c
            FROM Item__c
            WHERE Name = :BOOK_NAME
    ];
    Person__c borrower = [
            SELECT Id, Maximum_Number_Of_Rentals__c
            FROM Person__c
            WHERE Name = :BORROWER_NAME
    ];


    for (Integer i = 1; i <= 5; i++) {
      Loan__c loan = new Loan__c(
        Name = 'Test Loan',
        Item__c = book.Id,
        Borrower__c = borrower.Id,
        Status__c = Consts.LOANS.STATUS.BORROWED,
        Rental_Date__c = CURRENT_DATA.addDays(-(5 + 1)),
        End_Of_Rental__c = CURRENT_DATA.addDays(+i)
      );

      newLoans.add(loan);
    }

    insert newLoans;

    Test.startTest();
    DelayedItems scheduler = new DelayedItems();
    scheduler.execute(null);
    Test.stopTest();

    List<Loan__c> updatedLoans = [
      SELECT Id, Status__c
      FROM Loan__c
      WHERE Id IN :newLoans
    ];

    for (Loan__c updatedLoan : updatedLoans) {
      System.assertEquals(Consts.LOANS.STATUS.BORROWED, updatedLoan.Status__c);
    }
  }
}