force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Available</label>
    <type>Checkbox</type>

</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audiobook</fullName>
            </value>
            <value>
                <fullName>Magazine</fullName>
            </value>
            <value>
                <fullName>Paper Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <label>Borrower</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Item__c.Is_Available__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>

</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Maximum_Number_Of_Rentals__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Number_Of_Rentals__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Number Of Rentals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanTriggerHandler.cls
/**
 * Created by kamil on 07.07.2023.
 */

public class LoanTriggerHandler {
  public static void checkBookAvailability(List<Loan__c> newLoans) {
    Set<Id> requiredIDs = new Set<Id>();
    Map<Id, Loan__c> existingLoans = new Map<Id, Loan__c>();

    for (Loan__c loan : newLoans) {
      requiredIDs.add(loan.Item__c);
    }

    for (Loan__c existingLoan : [
      SELECT
        Item__c,
        Borrower__c,
        Item__r.Type__c,
        Borrower__r.Maximum_Number_Of_Rentals__c,
        Status__c
      FROM Loan__c
      WHERE
        Item__c IN :requiredIDs
        AND Status__c != :Consts.LOANS.STATUS.RETURNED
    ]) {
      existingLoans.put(existingLoan.Item__c, existingLoan);
    }

    for (Loan__c loan : newLoans) {
      if (existingLoans.containsKey(loan.Item__c)) {
        loan.addError(
          String.format(
            System.Label.CurrentlyBorrowedItem,
            new List<String>{ existingLoans.get(loan.Item__c).Item__r.Type__c }
          )
        );
      }
    }
  }

  public static void checkBookLimit(List<Loan__c> newLoans) {
    Set<Id> requiredIDs = new Set<Id>();
    Map<Id, Decimal> borrowers = new Map<Id, Decimal>();
    Map<Id, Decimal> maxLimitOfBooks = new Map<Id, Decimal>();

    for (Loan__c loan : newLoans) {
      requiredIDs.add(loan.Borrower__c);
    }

    for (Loan__c existingLoan : [
      SELECT
        Item__c,
        Borrower__c,
        Borrower__r.Maximum_Number_Of_Rentals__c,
        Status__c
      FROM Loan__c
      WHERE
        Borrower__c IN :requiredIDs
        AND Status__c != :Consts.LOANS.STATUS.RETURNED
    ]) {
      if (borrowers.containsKey(existingLoan.Borrower__c)) {
        borrowers.put(
          existingLoan.Borrower__c,
          borrowers.get(existingLoan.Borrower__c) + 1
        );
      } else {
        borrowers.put(existingLoan.Borrower__c, 1);
        maxLimitOfBooks.put(
          existingLoan.Borrower__c,
          existingLoan.Borrower__r.Maximum_Number_Of_Rentals__c
        );
      }
    }

    for (Loan__c loan : newLoans) {
      System.debug('Max wyporzyczen: ' + maxLimitOfBooks.get(loan.Borrower__c));
      if (
        borrowers.containsKey(loan.Borrower__c) &&
        borrowers.get(loan.Borrower__c) >= maxLimitOfBooks.get(loan.Borrower__c)
      ) {
        loan.addError(System.Label.MaxNumberOfBorrowing);
      }
    }
  }

  public static void changeAvailabilityStatus(List<Loan__c> loans, Boolean isDeleted){
    for(Loan__c loan : loans){
        if(loan.Status__c == Consts.LOANS.STATUS.RETURNED || isDeleted){
          loan.Item__r.Is_Available__c = true;
        }
      else{
        loan.Item__r.Is_Available__c = false;
      }
    }
  }
}