force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan #{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/End_Of_Rental__c.field-meta.xml
<CustomField>
    <fullName>End_Of_Rental__c</fullName>
    <label>End Of Rental</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservation</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DelayedItems.cls
public with sharing class DelayedItems implements Schedulable {
    public static final String JOB_NAME = 'Delayed Items Job';
    public static Id scheduleMe() {
        DelayedItems schedule = new DelayedItems();
        return System.schedule(JOB_NAME, Consts.CRONS.CRON.DELAYED_ITEMS, schedule);
    }

    public void execute(SchedulableContext sc) {
        Date currentDate = Date.today();

        List<Loan__c> overdueItems = [
                SELECT Id, Status__c
                FROM Loan__c
                WHERE
                        Status__c = :Consts.LOANS.STATUS.BORROWED
                        AND End_Of_Rental__c < :currentDate
        ];

        for (Loan__c loan : overdueItems) {
            loan.Status__c = Consts.LOANS.STATUS.DELAY;
        }

        update overdueItems;

    }
}