force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Encrypted_PIN__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_PIN__c</fullName>
    <label>Encrypted PIN</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/Tests/GenerateNewPinControllerTest.cls
/**
 * Created by kamil on 04.08.2023.
 */
@IsTest
public with sharing class GenerateNewPinControllerTest {
  @IsTest
  public static void generateNewPinTest() {
    List<Person__c> person = TestDataFactory.createPeopleList(
      1,
      true,
      'Test',
      'testemail',
      3
    );
    String oldPin = person.get(0).Encrypted_PIN__c;

    Test.startTest();
    GenerateNewPinController.generateNewPin(person.get(0).Id);
    Test.stopTest();

    person = [
      SELECT Id, Encrypted_PIN__c
      FROM Person__c
      WHERE Id = :person.get(0).Id
    ];

    Assert.areNotEqual(oldPin, person.get(0).Encrypted_PIN__c);
  }
}