force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/PersonTriggerHandler.cls
/**
 * Created by kamil on 20.07.2023.
 */

public with sharing class PersonTriggerHandler {
  public static void checkEmailAvailability(List<Person__c> people) {
    Set<String> emails = new Set<String>();
    List<String> unavailableEmails = new List<String>();
    for (Person__c person : people) {
      emails.add(person.Email__c);
    }

    for (Person__c person : [
      SELECT Email__c
      FROM Person__c
      WHERE Email__c IN :emails
    ]) {
      unavailableEmails.add(person.Email__c);
    }

    for (Person__c person : people) {
      if (unavailableEmails.contains(person.Email__c)) {
        person.addError(System.Label.UnavailableEmail);
      }
    }
  }
}