force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Encrypted_PIN__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_PIN__c</fullName>
    <label>Encrypted PIN</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person_ID__c.field-meta.xml
<CustomField>
    <fullName>Person_ID__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <externalId>true</externalId>
    <label>Person ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/GenerateNewPinController.cls
/**
 * Created by kamil on 04.08.2023.
 */

public with sharing class GenerateNewPinController {
  @AuraEnabled
  public static void generateNewPin(String personId) {
    List<Person__c> person = [
      SELECT
        Id,
        Email__c,
        Name,
        LastModifiedBy.Name,
        Person_ID__c,
        Encrypted_PIN__c
      FROM Person__c
      WHERE Id = :personId
    ];
    UserUtils.generatePIN(person);
    update person;
    UserUtils.sendNewPinData(person);
  }
}