force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Encrypted_PIN__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_PIN__c</fullName>
    <label>Encrypted PIN</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/UserUtils.cls
/**
 * Created by kamil on 04.08.2023.
 */

public with sharing class UserUtils {
  @TestVisible
  private static final String NEW_PIN_SUBJECT = 'New PIN';

  public static void generatePIN(List<Person__c> newPeople) {
    for (Person__c person : newPeople) {
      person.Encrypted_PIN__c = String.valueOf(generateRandomLong());
    }
  }

  public static void sendNewPinData(List<Person__c> newPeople) {
    List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();

    for (Person__c person : newPeople) {
      mails.add(
        EmailManager.createSingleEmail(
          person.Email__c,
          String.format(
            Label.NewPinMessage,
            new List<String>{ person.Encrypted_PIN__c }
          ),
          NEW_PIN_SUBJECT
        )
      );
    }

    Messaging.sendEmail(mails);
  }

  public static Long generateRandomLong() {
    Integer randomInt = (Integer) (Math.random() * (99999 - 10000 + 1) + 10000);

    String timestampString =
      String.valueOf(randomInt) +
      String.valueOf(System.currentTimeMillis()).right(5);

    return Long.valueOf(timestampString);
  }
}